name: eShopOnWeb Build and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Build with dotnet Web
      run: dotnet build ./Web/Web.csproj --configuration Release
      
    - name: Build with dotnet API
      run: dotnet build ./PublicApi/PublicApi.csproj --configuration Release
